### ISSUE TITLE
Video Stop After Logout

### ISSUE THREAD

**Issue by shripadkulkarnid** [luceefer/iOS-Parallax-Demo#3]
video stop after logout.How to solve this please guide?
Thank you in advance

**Comment by moonlsd** [comment]
Hi @shripadkulkarid,

What do you mean by "video stop after logout"? In my demo, there is only one login screen and I did not have login feature.

The video is controlled by iOS framework, if you want to know about media playback and processing in iOS, then take a look at AVFoundation.

**Comment by shripadkulkarnid** [comment]
Ok
